using System.Collections.Generic;

namespace Snowberry.Mediator.SourceGenerator;

/// <summary>Emits the reflection-free registration source from a <see cref="DiscoveryModel"/>.</summary>
internal static class Emitter
{
    /// <summary>Emits the reflection-free registration source for the discovered handlers.</summary>
    /// <param name="model">The discovery model to emit.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(in DiscoveryModel model)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line();

        EmitRegistrationClass(w, model);

        if (model.HasMicrosoftDI)
        {
            w.Line();
            EmitMicrosoftEntryPoint(w);
        }

        if (model.HasSnowberryDI)
        {
            w.Line();
            EmitSnowberryEntryPoint(w);
        }

        return w.ToString();
    }

    private static void EmitRegistrationClass(CodeWriter w, in DiscoveryModel model)
    {
        bool hasOpenRequestBehavior = HasOpen(model, isStream: false);
        bool hasOpenStreamBehavior = HasOpen(model, isStream: true);

        w.Open($"namespace {WellKnown.GeneratedNamespace}");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"Snowberry.Mediator.SourceGenerator\", null)]");
        w.Open("internal static class SnowberryMediatorRegistration");

        w.Open($"internal static void Register({WellKnown.FqIServiceContext} ctx, {WellKnown.FqRegistrationServiceLifetime} lifetime, bool append)");

        w.Line($"if (!append || !ctx.IsServiceRegistered<{WellKnown.FqMediatorInterface}>())");
        w.Line($"    ctx.TryRegister(typeof({WellKnown.FqMediatorInterface}), typeof({WellKnown.FqMediator}), lifetime);");

        EmitRequestHandlers(w, model);
        EmitPipelineBlock(w, model, isStream: false, hasOpenRequestBehavior);
        EmitPipelineBlock(w, model, isStream: true, hasOpenStreamBehavior);
        EmitNotificationBlock(w, model);

        w.Close(); // Register

        if (hasOpenRequestBehavior)
            EmitResolver(w, model, isStream: false, methodName: "CloseRequestPipeline");

        if (hasOpenStreamBehavior)
            EmitResolver(w, model, isStream: true, methodName: "CloseStreamPipeline");

        w.Close(); // class
        w.Close(); // namespace
    }

    private static void EmitRequestHandlers(CodeWriter w, in DiscoveryModel model)
    {
        bool any = false;
        foreach (var handler in model.RequestHandlers)
        {
            if (!any)
            {
                w.Line();
                w.Line("// Request and stream request handlers.");
                any = true;
            }

            string iface = handler.IsStream ? WellKnown.FqStreamRequestHandlerInterface : WellKnown.FqRequestHandlerInterface;
            w.Line($"ctx.TryRegister(typeof({iface}<{handler.RequestFqn}, {handler.ResponseFqn}>), typeof({handler.HandlerFqn}), lifetime);");
        }
    }

    private static void EmitPipelineBlock(CodeWriter w, in DiscoveryModel model, bool isStream, bool hasOpen)
    {
        var behaviors = new List<BehaviorModel>();
        foreach (var b in model.Behaviors)
        {
            if (b.IsStream == isStream)
                behaviors.Add(b);
        }

        if (behaviors.Count == 0)
            return;

        string registryType = isStream ? WellKnown.FqGlobalStreamPipelineRegistry : WellKnown.FqGlobalPipelineRegistry;
        string registryIface = isStream ? WellKnown.FqIGlobalStreamPipelineRegistry : WellKnown.FqIGlobalPipelineRegistry;
        string infoType = isStream ? WellKnown.FqStreamPipelineBehaviorHandlerInfo : WellKnown.FqPipelineBehaviorHandlerInfo;
        string resolver = isStream ? "CloseStreamPipeline" : "CloseRequestPipeline";
        string registry = isStream ? "streamPipeline" : "pipeline";
        string found = isStream ? "foundStreamPipeline" : "foundPipeline";
        string newExpr = $"new {registryType}({(hasOpen ? resolver : string.Empty)})";

        w.Line();
        w.Line($"// {(isStream ? "Stream pipeline" : "Pipeline")} behaviors.");
        EmitRegistryGetOrCreate(w, registryIface, newExpr, registry, found);

        foreach (var b in behaviors)
        {
            w.Line($"{registry}!.Register(new {infoType}");
            w.OpenBrace();

            if (b.IsOpenGeneric)
            {
                if (b.HasPriority)
                    w.Line($"HandlerType = typeof({b.OpenHandlerTypeOf}),");
                else
                    w.Line($"HandlerType = typeof({b.OpenHandlerTypeOf})");
            }
            else
            {
                w.Line($"HandlerType = typeof({b.HandlerFqn}),");
                w.Line($"RequestType = typeof({b.RequestFqn}),");
                if (b.HasPriority)
                    w.Line($"ResponseType = typeof({b.ResponseFqn}),");
                else
                    w.Line($"ResponseType = typeof({b.ResponseFqn})");
            }

            if (b.HasPriority)
                w.Line($"PriorityOverride = {b.Priority}");

            w.Close(");");

            if (b.IsOpenGeneric)
            {
                foreach (var closed in b.ClosedInstances)
                    w.Line($"ctx.TryRegister(typeof({closed.ClosedHandlerFqn}), typeof({closed.ClosedHandlerFqn}), lifetime);");
            }
            else
            {
                w.Line($"ctx.TryRegister(typeof({b.HandlerFqn}), typeof({b.HandlerFqn}), lifetime);");
            }
        }

        w.Line($"{registry}!.Build();");
    }

    private static void EmitNotificationBlock(CodeWriter w, in DiscoveryModel model)
    {
        if (model.NotificationHandlers.Count == 0)
            return;

        string registryIface = $"{WellKnown.FqIGlobalNotificationHandlerRegistry}<{WellKnown.FqNotificationHandlerInfo}>";

        w.Line();
        w.Line("// Notification handlers (open-generic handlers flattened to closed registrations).");
        EmitRegistryGetOrCreate(w, registryIface, $"new {WellKnown.FqGlobalNotificationHandlerRegistry}()", "notifications", "foundNotifications");

        foreach (var handler in model.NotificationHandlers)
        {
            w.Line($"notifications!.Register(new {WellKnown.FqNotificationHandlerInfo}");
            w.OpenBrace();
            w.Line($"HandlerType = typeof({handler.HandlerFqn}),");
            w.Line($"NotificationType = typeof({handler.NotificationFqn})");
            w.Close(");");
            w.Line($"ctx.TryRegister(typeof({handler.HandlerFqn}), typeof({handler.HandlerFqn}), lifetime);");
        }

        w.Line("notifications!.Build();");
    }

    /// <summary>
    /// Emits a nullable registry local that is created and registered when not appending (or when no registry
    /// of the given type is registered yet), and otherwise reuses the existing singleton so that appended
    /// registrations extend the configured registry instead of being discarded.
    /// </summary>
    /// <param name="w">The code writer.</param>
    /// <param name="iface">The fully-qualified registry interface used as both the service type and the singleton key.</param>
    /// <param name="newExpr">The expression that constructs a fresh registry instance.</param>
    /// <param name="varName">The name of the emitted registry local.</param>
    /// <param name="foundVar">The name of the emitted <see langword="out"/> flag for the singleton lookup.</param>
    private static void EmitRegistryGetOrCreate(CodeWriter w, string iface, string newExpr, string varName, string foundVar)
    {
        w.Line($"{iface}? {varName};");
        w.Open($"if (!append || !ctx.IsServiceRegistered<{iface}>())");
        w.Line($"{varName} = {newExpr};");
        w.Line($"ctx.TryRegister(typeof({iface}), {varName});");
        w.Close();
        w.Open("else");
        w.Line($"{varName} = ctx.TryToGetSingleton<{iface}>(out bool {foundVar});");
        w.Open($"if (!{foundVar})");
        w.Line($"{varName} = {newExpr};");
        w.Line($"ctx.TryRegister(typeof({iface}), {varName});");
        w.Close();
        w.Close();
    }

    private static void EmitResolver(CodeWriter w, in DiscoveryModel model, bool isStream, string methodName)
    {
        const string justification = "All discovered request/response pairs resolve to a statically-known closed type; the MakeGenericType fallback is unreachable under closed-world AOT.";

        w.Line();
        w.Line($"[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2055\", Justification = \"{justification}\")]");
        w.Line($"[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"{justification}\")]");
        w.Open($"private static global::System.Type {methodName}(global::System.Type open, global::System.Type request, global::System.Type response)");

        foreach (var b in model.Behaviors)
        {
            if (b.IsStream != isStream || !b.IsOpenGeneric || b.ClosedInstances.Count == 0)
                continue;

            w.Open($"if (open == typeof({b.OpenHandlerTypeOf}))");
            foreach (var closed in b.ClosedInstances)
            {
                w.Line($"if (request == typeof({closed.RequestFqn}) && response == typeof({closed.ResponseFqn}))");
                w.Line($"    return typeof({closed.ClosedHandlerFqn});");
            }

            w.Close();
        }

        w.Line("return open.MakeGenericType(request, response);");
        w.Close();
    }

    private static void EmitMicrosoftEntryPoint(CodeWriter w)
    {
        w.Open("namespace Microsoft.Extensions.DependencyInjection");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"Snowberry.Mediator.SourceGenerator\", null)]");
        w.Open("public static class SnowberryMediatorServiceCollectionExtensions");

        w.Line("/// <summary>Registers all discovered mediator handlers, behaviors and notification handlers without reflection.</summary>");
        w.Line("/// <param name=\"services\">The service collection.</param>");
        w.Line("/// <param name=\"lifetime\">The lifetime applied to the mediator and handler registrations.</param>");
        w.Line("/// <param name=\"append\">Whether to append to existing registrations instead of replacing them.</param>");
        w.Line("/// <returns>The same service collection, for chaining.</returns>");
        w.Open($"public static {WellKnown.FqMicrosoftServiceCollection} AddSnowberryMediator(this {WellKnown.FqMicrosoftServiceCollection} services, {WellKnown.FqMicrosoftServiceLifetime} lifetime = {WellKnown.FqMicrosoftServiceLifetime}.Scoped, bool append = false)");
        w.Line($"var ctx = {WellKnown.FqMicrosoftServiceContext}.Create(services);");
        w.Line($"{WellKnown.FqGeneratedRegistration}.Register(ctx, Map(lifetime), append);");
        w.Line("return services;");
        w.Close();

        EmitLifetimeMap(w, WellKnown.FqMicrosoftServiceLifetime);

        w.Close(); // class
        w.Close(); // namespace
    }

    private static void EmitSnowberryEntryPoint(CodeWriter w)
    {
        w.Open("namespace Snowberry.Mediator.DependencyInjection");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"Snowberry.Mediator.SourceGenerator\", null)]");
        w.Open("public static class SnowberryMediatorServiceRegistryExtensions");

        w.Line("/// <summary>Registers all discovered mediator handlers, behaviors and notification handlers without reflection.</summary>");
        w.Line("/// <param name=\"registry\">The service registry.</param>");
        w.Line("/// <param name=\"lifetime\">The lifetime applied to the mediator and handler registrations.</param>");
        w.Line("/// <param name=\"append\">Whether to append to existing registrations instead of replacing them.</param>");
        w.Line("/// <returns>The same service registry, for chaining.</returns>");
        w.Open($"public static {WellKnown.FqSnowberryServiceRegistry} AddSnowberryMediator(this {WellKnown.FqSnowberryServiceRegistry} registry, {WellKnown.FqSnowberryServiceLifetime} lifetime = {WellKnown.FqSnowberryServiceLifetime}.Scoped, bool append = false)");
        w.Line($"var ctx = {WellKnown.FqSnowberryServiceContext}.Create(registry);");
        w.Line($"{WellKnown.FqGeneratedRegistration}.Register(ctx, Map(lifetime), append);");
        w.Line("return registry;");
        w.Close();

        EmitLifetimeMap(w, WellKnown.FqSnowberryServiceLifetime);

        w.Close(); // class
        w.Close(); // namespace
    }

    private static void EmitLifetimeMap(CodeWriter w, string sourceLifetime)
    {
        w.Open($"private static {WellKnown.FqRegistrationServiceLifetime} Map({sourceLifetime} lifetime)");
        w.Line("return lifetime switch");
        w.OpenBrace();
        w.Line($"{sourceLifetime}.Singleton => {WellKnown.FqRegistrationServiceLifetime}.Singleton,");
        w.Line($"{sourceLifetime}.Transient => {WellKnown.FqRegistrationServiceLifetime}.Transient,");
        w.Line($"_ => {WellKnown.FqRegistrationServiceLifetime}.Scoped,");
        w.Close(";");
        w.Close();
    }

    private static bool HasOpen(in DiscoveryModel model, bool isStream)
    {
        foreach (var b in model.Behaviors)
        {
            if (b.IsStream == isStream && b.IsOpenGeneric && b.ClosedInstances.Count > 0)
                return true;
        }

        return false;
    }
}
