using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Snowberry.Mediator.SourceGenerator;

/// <summary>Tracking names for the incremental pipeline steps, used to assert generator cacheability.</summary>
public static class TrackingNames
{
    /// <summary>The tracking name of the discovery step that produces the registration model.</summary>
    public const string c_Discovery = "Discovery";
}

/// <summary>
/// Incremental source generator that discovers Snowberry.Mediator handlers, behaviors and notification
/// handlers at compile time (across the compilation and referenced assemblies) and emits reflection-free,
/// AOT-friendly registration code. Opt in with <c>[assembly: SnowberryMediator]</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SnowberryMediatorGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SnowberryMediatorAttribute.g.cs", SourceText.From(c_AttributeSource, Encoding.UTF8)));

        var provider = context.CompilationProvider
            .Select(static (compilation, ct) => Discovery.Discover(compilation, ct))
            .WithTrackingName(TrackingNames.c_Discovery);

        context.RegisterSourceOutput(provider, static (ctx, model) => Execute(ctx, model));
    }

    private static void Execute(SourceProductionContext ctx, DiscoveryModel? model)
    {
        if (model is not { } discovery)
            return;

        foreach (var diagnostic in discovery.Diagnostics)
            ctx.ReportDiagnostic(diagnostic.ToDiagnostic());

        if (!discovery.HasAnyHandlers)
            return;

        ctx.AddSource("SnowberryMediator.Registration.g.cs", SourceText.From(Emitter.Emit(discovery), Encoding.UTF8));
    }

    private const string c_AttributeSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace Snowberry.Mediator
        {
            /// <summary>
            /// Opt-in marker that triggers Snowberry.Mediator source-generated, reflection-free handler
            /// registration for the assembly it is applied to (typically the composition-root project).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("Snowberry.Mediator.SourceGenerator", null)]
            internal sealed class SnowberryMediatorAttribute : global::System.Attribute
            {
                /// <summary>Register discovered <c>IRequestHandler&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
                public bool RegisterRequestHandlers { get; set; } = true;

                /// <summary>Register discovered <c>IStreamRequestHandler&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
                public bool RegisterStreamRequestHandlers { get; set; } = true;

                /// <summary>Register discovered <c>INotificationHandler&lt;&gt;</c> implementations. Default <see langword="true"/>.</summary>
                public bool RegisterNotificationHandlers { get; set; } = true;

                /// <summary>Register discovered <c>IPipelineBehavior&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
                public bool RegisterPipelineBehaviors { get; set; } = true;

                /// <summary>Register discovered <c>IStreamPipelineBehavior&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
                public bool RegisterStreamPipelineBehaviors { get; set; } = true;
            }
        }
        """;
}
