//HintName: SnowberryMediatorAttribute.g.cs
// <auto-generated/>
#nullable enable
namespace Snowberry.Mediator
{
    /// <summary>
    /// Opt-in marker that triggers Snowberry.Mediator source-generated, reflection-free handler
    /// registration for the assembly it is applied to (typically the composition-root project).
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCode("Snowberry.Mediator.SourceGenerator", null)]
    internal sealed class SnowberryMediatorAttribute : global::System.Attribute
    {
        /// <summary>Register discovered <c>IRequestHandler&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
        public bool RegisterRequestHandlers { get; set; } = true;

        /// <summary>Register discovered <c>IStreamRequestHandler&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
        public bool RegisterStreamRequestHandlers { get; set; } = true;

        /// <summary>Register discovered <c>INotificationHandler&lt;&gt;</c> implementations. Default <see langword="true"/>.</summary>
        public bool RegisterNotificationHandlers { get; set; } = true;

        /// <summary>Register discovered <c>IPipelineBehavior&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
        public bool RegisterPipelineBehaviors { get; set; } = true;

        /// <summary>Register discovered <c>IStreamPipelineBehavior&lt;,&gt;</c> implementations. Default <see langword="true"/>.</summary>
        public bool RegisterStreamPipelineBehaviors { get; set; } = true;
    }
}