//HintName: SnowberryMediator.Registration.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

namespace Snowberry.Mediator.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("Snowberry.Mediator.SourceGenerator", null)]
    internal static class SnowberryMediatorRegistration
    {
        internal static void Register(global::Snowberry.Mediator.DependencyInjection.Shared.Contracts.IServiceContext ctx, global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime lifetime, bool append)
        {
            if (!append || !ctx.IsServiceRegistered<global::Snowberry.Mediator.Abstractions.IMediator>())
                ctx.TryRegister(typeof(global::Snowberry.Mediator.Abstractions.IMediator), typeof(global::Snowberry.Mediator.Mediator), lifetime);

            // Request and stream request handlers.
            ctx.TryRegister(typeof(global::Snowberry.Mediator.Abstractions.Handler.IRequestHandler<global::App.GetUser, string>), typeof(global::App.GetUserHandler), lifetime);

            // Pipeline behaviors.
            global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry? pipeline;
            if (!append && ctx.IsServiceRegistered<global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry>())
                throw new global::System.InvalidOperationException("Snowberry.Mediator is already registered on this container. Call AddSnowberryMediator with append: true to add more registrations.");
            if (!append || !ctx.IsServiceRegistered<global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry>())
            {
                pipeline = new global::Snowberry.Mediator.Registries.GlobalPipelineRegistry(CloseRequestPipeline);
                ctx.TryRegister(typeof(global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry), pipeline);
            }
            else
            {
                pipeline = ctx.TryToGetSingleton<global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry>(out bool foundPipeline);
                if (!foundPipeline)
                {
                    pipeline = new global::Snowberry.Mediator.Registries.GlobalPipelineRegistry(CloseRequestPipeline);
                    ctx.TryRegister(typeof(global::Snowberry.Mediator.Registries.Contracts.IGlobalPipelineRegistry), pipeline);
                }
            }
            pipeline!.Register(new global::Snowberry.Mediator.Models.PipelineBehaviorHandlerInfo
            {
                HandlerType = typeof(global::App.LoggingBehavior<,>),
                PriorityOverride = 50
            });
            ctx.TryRegister(typeof(global::App.LoggingBehavior<global::App.GetUser, string>), typeof(global::App.LoggingBehavior<global::App.GetUser, string>), lifetime);
            pipeline!.Build();

            // Notification handlers (open-generic handlers flattened to closed registrations).
            global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>? notifications;
            if (!append && ctx.IsServiceRegistered<global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>>())
                throw new global::System.InvalidOperationException("Snowberry.Mediator is already registered on this container. Call AddSnowberryMediator with append: true to add more registrations.");
            if (!append || !ctx.IsServiceRegistered<global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>>())
            {
                notifications = new global::Snowberry.Mediator.Registries.GlobalNotificationHandlerRegistry();
                ctx.TryRegister(typeof(global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>), notifications);
            }
            else
            {
                notifications = ctx.TryToGetSingleton<global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>>(out bool foundNotifications);
                if (!foundNotifications)
                {
                    notifications = new global::Snowberry.Mediator.Registries.GlobalNotificationHandlerRegistry();
                    ctx.TryRegister(typeof(global::Snowberry.Mediator.Registries.Contracts.IGlobalNotificationHandlerRegistry<global::Snowberry.Mediator.Models.NotificationHandlerInfo>), notifications);
                }
            }
            notifications!.Register(new global::Snowberry.Mediator.Models.NotificationHandlerInfo
            {
                HandlerType = typeof(global::App.UserCreatedHandler),
                NotificationType = typeof(global::App.UserCreated)
            });
            ctx.TryRegister(typeof(global::App.UserCreatedHandler), typeof(global::App.UserCreatedHandler), lifetime);
            notifications!.Build();
        }

        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2055", Justification = "All discovered request/response pairs resolve to a statically-known closed type; the MakeGenericType fallback is unreachable under closed-world AOT.")]
        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = "All discovered request/response pairs resolve to a statically-known closed type; the MakeGenericType fallback is unreachable under closed-world AOT.")]
        private static global::System.Type CloseRequestPipeline(global::System.Type open, global::System.Type request, global::System.Type response)
        {
            if (open == typeof(global::App.LoggingBehavior<,>))
            {
                if (request == typeof(global::App.GetUser) && response == typeof(string))
                    return typeof(global::App.LoggingBehavior<global::App.GetUser, string>);
            }
            return open.MakeGenericType(request, response);
        }
    }
}

namespace Microsoft.Extensions.DependencyInjection
{
    [global::System.CodeDom.Compiler.GeneratedCode("Snowberry.Mediator.SourceGenerator", null)]
    public static class SnowberryMediatorServiceCollectionExtensions
    {
        /// <summary>Registers all discovered mediator handlers, behaviors and notification handlers without reflection.</summary>
        /// <param name="services">The service collection.</param>
        /// <param name="lifetime">The lifetime applied to the mediator and handler registrations.</param>
        /// <param name="append">Whether to append to existing registrations instead of replacing them.</param>
        /// <returns>The same service collection, for chaining.</returns>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSnowberryMediator(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped, bool append = false)
        {
            var ctx = global::Snowberry.Mediator.Extensions.DependencyInjection.MicrosoftServiceContext.Create(services);
            global::Snowberry.Mediator.Generated.SnowberryMediatorRegistration.Register(ctx, Map(lifetime), append);
            return services;
        }
        private static global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime Map(global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime)
        {
            return lifetime switch
            {
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Singleton,
                global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Transient,
                _ => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Scoped,
            };
        }
    }
}

namespace Snowberry.Mediator.DependencyInjection
{
    [global::System.CodeDom.Compiler.GeneratedCode("Snowberry.Mediator.SourceGenerator", null)]
    public static class SnowberryMediatorServiceRegistryExtensions
    {
        /// <summary>Registers all discovered mediator handlers, behaviors and notification handlers without reflection.</summary>
        /// <param name="registry">The service registry.</param>
        /// <param name="lifetime">The lifetime applied to the mediator and handler registrations.</param>
        /// <param name="append">Whether to append to existing registrations instead of replacing them.</param>
        /// <returns>The same service registry, for chaining.</returns>
        public static global::Snowberry.DependencyInjection.Abstractions.Interfaces.IServiceRegistry AddSnowberryMediator(this global::Snowberry.DependencyInjection.Abstractions.Interfaces.IServiceRegistry registry, global::Snowberry.DependencyInjection.Abstractions.ServiceLifetime lifetime = global::Snowberry.DependencyInjection.Abstractions.ServiceLifetime.Scoped, bool append = false)
        {
            var ctx = global::Snowberry.Mediator.DependencyInjection.SnowberryServiceContext.Create(registry);
            global::Snowberry.Mediator.Generated.SnowberryMediatorRegistration.Register(ctx, Map(lifetime), append);
            return registry;
        }
        private static global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime Map(global::Snowberry.DependencyInjection.Abstractions.ServiceLifetime lifetime)
        {
            return lifetime switch
            {
                global::Snowberry.DependencyInjection.Abstractions.ServiceLifetime.Singleton => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Singleton,
                global::Snowberry.DependencyInjection.Abstractions.ServiceLifetime.Transient => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Transient,
                _ => global::Snowberry.Mediator.DependencyInjection.Shared.RegistrationServiceLifetime.Scoped,
            };
        }
    }
}
